export const scenarioPresets = [
  {
    id: 'corridor-inspection',
    title: '走廊巡检场景',
    category: '导航实验',
    difficulty: '中等',
    summary: '模拟狭长室内走廊中的障碍分布，用于验证超声波和红外传感器在约束通道中的感知稳定性。',
    objectives: [
      '验证超声波在狭窄路径中的测距稳定性',
      '观察红外传感器在中等环境光下的响应变化',
      '分析机器人多次转向时 IMU 航向漂移情况',
    ],
    metrics: ['距离偏差', '超量程次数', '航向漂移'],
    scene: {
      sceneId: 'corridor_inspection',
      ambientLight: 0.42,
      robot: { x: 1.4, y: 2.2, theta: 0, vx: 0, vy: 0 },
      obstacles: [
        { id: 'ob_corr_1', x: 4.4, y: 2.1, width: 0.8, height: 2.9, material: 'wall', reflectivity: 0.85 },
        { id: 'ob_corr_2', x: 7.2, y: 4.8, width: 0.9, height: 2.4, material: 'wall', reflectivity: 0.9 },
        { id: 'ob_corr_3', x: 7.1, y: 1.2, width: 0.9, height: 2.2, material: 'wall', reflectivity: 0.8 },
        { id: 'ob_corr_4', x: 9.2, y: 3.0, width: 0.8, height: 4.0, material: 'door', reflectivity: 0.62 },
      ],
    },
    sensors: [
      {
        sensorType: 'ultrasonic',
        name: '前向超声波',
        mountX: 0.35,
        mountY: 0,
        mountAngle: 0,
        rangeCm: 350,
        beamDeg: 28,
        frequency: 12,
        noise: 0.015,
        sysError: 0.01,
      },
      {
        sensorType: 'infrared',
        sensorId: 'infrared_corridor_left',
        name: '左侧红外',
        mountX: 0.25,
        mountY: 0.16,
        mountAngle: 0.45,
        rangeCm: 80,
        frequency: 20,
        noise: 0.05,
        sensitivity: 1.1,
        outputMode: 'analog',
        threshold: 0.4,
      },
      {
        sensorType: 'infrared',
        sensorId: 'infrared_corridor_right',
        name: '右侧红外',
        mountX: 0.25,
        mountY: -0.16,
        mountAngle: -0.45,
        rangeCm: 80,
        frequency: 20,
        noise: 0.05,
        sensitivity: 1.1,
        outputMode: 'analog',
        threshold: 0.4,
      },
      {
        sensorType: 'imu',
        name: '主控 IMU',
        frequency: 60,
        noiseGyro: 0.02,
        noiseAccel: 0.12,
        driftCoeff: 0.003,
      },
    ],
  },
  {
    id: 'warehouse-scan',
    title: '仓储扫描场景',
    category: '避障实验',
    difficulty: '较高',
    summary: '模拟货架密集的仓储环境，用不同反射率材质验证多传感器混合部署的综合表现。',
    objectives: [
      '比较超声波与红外在混合材质周围的一致性',
      '验证多通道传感器管理界面的稳定性',
      '生成高频采样数据用于图表与导出展示',
    ],
    metrics: ['命中率', '告警频次', '采样吞吐量'],
    scene: {
      sceneId: 'warehouse_scan',
      ambientLight: 0.28,
      robot: { x: 2.0, y: 2.8, theta: 0.15, vx: 0, vy: 0 },
      obstacles: [
        { id: 'rack_1', x: 4.2, y: 5.6, width: 1.4, height: 1.0, material: 'metal', reflectivity: 0.92 },
        { id: 'rack_2', x: 6.6, y: 4.7, width: 1.4, height: 1.4, material: 'metal', reflectivity: 0.88 },
        { id: 'rack_3', x: 8.9, y: 3.4, width: 1.2, height: 1.8, material: 'wood', reflectivity: 0.6 },
        { id: 'rack_4', x: 10.0, y: 6.0, width: 1.0, height: 1.2, material: 'plastic', reflectivity: 0.48 },
        { id: 'rack_5', x: 8.0, y: 1.6, width: 1.6, height: 1.0, material: 'wood', reflectivity: 0.58 },
      ],
    },
    sensors: [
      {
        sensorType: 'ultrasonic',
        name: '前向宽波束超声波',
        mountX: 0.35,
        mountY: 0,
        mountAngle: 0,
        rangeCm: 420,
        beamDeg: 44,
        frequency: 10,
        noise: 0.02,
        sysError: 0.02,
      },
      {
        sensorType: 'ultrasonic',
        sensorId: 'ultrasonic_left',
        name: '左侧超声波',
        mountX: 0.22,
        mountY: 0.18,
        mountAngle: 0.75,
        rangeCm: 260,
        beamDeg: 24,
        frequency: 12,
        noise: 0.018,
        sysError: 0.01,
      },
      {
        sensorType: 'ultrasonic',
        sensorId: 'ultrasonic_right',
        name: '右侧超声波',
        mountX: 0.22,
        mountY: -0.18,
        mountAngle: -0.75,
        rangeCm: 260,
        beamDeg: 24,
        frequency: 12,
        noise: 0.018,
        sysError: 0.01,
      },
      {
        sensorType: 'infrared',
        name: '前向红外',
        mountX: 0.28,
        mountY: 0,
        mountAngle: 0,
        rangeCm: 70,
        frequency: 24,
        noise: 0.05,
        sensitivity: 1.3,
        outputMode: 'analog',
        threshold: 0.46,
      },
      {
        sensorType: 'imu',
        name: '导航 IMU',
        frequency: 70,
        noiseGyro: 0.018,
        noiseAccel: 0.1,
        driftCoeff: 0.0025,
      },
    ],
  },
  {
    id: 'crossroad-calibration',
    title: '十字路口标定场景',
    category: '标定实验',
    difficulty: '基础',
    summary: '适合进行基线测量与快速演示的开放场景，可用于标定传感器参数和复位对比。',
    objectives: [
      '在简单地图下采集基线数据',
      '演示场景重置与参数复位功能',
      '为复杂场景实验提供参数标定参考',
    ],
    metrics: ['基线均值', '噪声范围', '重置一致性'],
    scene: {
      sceneId: 'crossroad_calibration',
      ambientLight: 0.36,
      robot: { x: 2.3, y: 2.5, theta: -0.2, vx: 0, vy: 0 },
      obstacles: [
        { id: 'cross_1', x: 5.8, y: 2.6, width: 1.1, height: 1.1, material: 'foam', reflectivity: 0.43 },
        { id: 'cross_2', x: 8.0, y: 5.4, width: 1.4, height: 1.0, material: 'wood', reflectivity: 0.72 },
        { id: 'cross_3', x: 8.3, y: 1.1, width: 1.4, height: 1.0, material: 'wood', reflectivity: 0.72 },
      ],
    },
    sensors: [
      {
        sensorType: 'ultrasonic',
        name: '标定超声波',
        mountX: 0.34,
        mountY: 0,
        mountAngle: 0,
        rangeCm: 300,
        beamDeg: 35,
        frequency: 9,
        noise: 0.012,
        sysError: 0.008,
      },
      {
        sensorType: 'infrared',
        name: '标定红外',
        mountX: 0.26,
        mountY: 0,
        mountAngle: 0,
        rangeCm: 60,
        frequency: 18,
        noise: 0.04,
        sensitivity: 1,
        outputMode: 'analog',
        threshold: 0.42,
      },
      {
        sensorType: 'imu',
        name: '参考 IMU',
        frequency: 50,
        noiseGyro: 0.015,
        noiseAccel: 0.08,
        driftCoeff: 0.0015,
      },
    ],
  },
  {
    id: 'perimeter-patrol',
    title: '周界巡航场景',
    category: '长时运行',
    difficulty: '中等',
    summary: '适用于长时间采样、日志积累和导出验证的环形边界场景，便于观察长时运行稳定性。',
    objectives: [
      '进行长时运行并积累日志与曲线数据',
      '验证数据导出与长时采样流程的完整性',
      '观察漂移与事件密度随时间的变化',
    ],
    metrics: ['运行时长', '日志密度', '记录完整性'],
    scene: {
      sceneId: 'perimeter_patrol',
      ambientLight: 0.33,
      robot: { x: 1.5, y: 1.8, theta: 0.4, vx: 0, vy: 0 },
      obstacles: [
        { id: 'per_1', x: 4.0, y: 1.0, width: 2.2, height: 0.7, material: 'wall', reflectivity: 0.82 },
        { id: 'per_2', x: 8.0, y: 1.2, width: 2.3, height: 0.7, material: 'wall', reflectivity: 0.82 },
        { id: 'per_3', x: 10.5, y: 4.0, width: 0.8, height: 5.0, material: 'wall', reflectivity: 0.86 },
        { id: 'per_4', x: 7.2, y: 7.1, width: 5.2, height: 0.8, material: 'wall', reflectivity: 0.78 },
        { id: 'per_5', x: 2.4, y: 6.8, width: 2.6, height: 0.8, material: 'wall', reflectivity: 0.78 },
        { id: 'per_6', x: 1.0, y: 4.2, width: 0.8, height: 4.6, material: 'wall', reflectivity: 0.85 },
      ],
    },
    sensors: [
      {
        sensorType: 'ultrasonic',
        name: '巡航前向超声波',
        mountX: 0.35,
        mountY: 0,
        mountAngle: 0,
        rangeCm: 380,
        beamDeg: 26,
        frequency: 11,
        noise: 0.016,
        sysError: 0.012,
      },
      {
        sensorType: 'infrared',
        name: '近距离红外',
        mountX: 0.18,
        mountY: 0.1,
        mountAngle: 0.3,
        rangeCm: 55,
        frequency: 22,
        noise: 0.05,
        sensitivity: 1.15,
        outputMode: 'analog',
        threshold: 0.45,
      },
      {
        sensorType: 'imu',
        name: '巡航 IMU',
        frequency: 65,
        noiseGyro: 0.02,
        noiseAccel: 0.09,
        driftCoeff: 0.002,
      },
    ],
  },
];

export const architectureNotes = [
  {
    title: '前端展示层',
    points: [
      '采用 Vue 3 构建多页面单页应用壳，统一管理工作台、分析页与使用说明页',
      '使用 Canvas 完成机器人、障碍物与感知范围的可视化编辑',
      '通过 ECharts 展示实时曲线，并提供数据筛选与导出能力',
    ],
  },
  {
    title: '后端仿真层',
    points: [
      '基于 WebSocket 持续维护场景状态、传感器参数和运行状态',
      '分别实现超声波、红外与 IMU 的采样模型，输出实时传感数据',
      '通过校验模块保护场景更新、障碍物编辑与传感器配置的合法性',
    ],
  },
  {
    title: '实验流程层',
    points: [
      '通过预设场景实现可重复的实验初始化',
      '依靠日志与曲线完成运行过程的观察和记录',
      '结合数据分析页提炼运行质量、异常分布与调参建议',
    ],
  },
];

export function getPresetById(id) {
  return scenarioPresets.find((item) => item.id === id) ?? null;
}

export function clonePresetBundle(preset) {
  return JSON.parse(JSON.stringify(preset));
}
